# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minitwitter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'minitwitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\x12\x0bminitwitter\"%\n\x12SendMessageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"&\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x12GetMessagesRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"=\n\x13GetMessagesResponse\x12&\n\x08messages\x18\x01 \x03(\x0b\x32\x14.minitwitter.Message\"-\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\xb1\x01\n\x0bMiniTwitter\x12P\n\x0bSendMessage\x12\x1f.minitwitter.SendMessageRequest\x1a .minitwitter.SendMessageResponse\x12P\n\x0bGetMessages\x12\x1f.minitwitter.GetMessagesRequest\x1a .minitwitter.GetMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=34
  _globals['_SENDMESSAGEREQUEST']._serialized_end=71
  _globals['_SENDMESSAGERESPONSE']._serialized_start=73
  _globals['_SENDMESSAGERESPONSE']._serialized_end=111
  _globals['_GETMESSAGESREQUEST']._serialized_start=113
  _globals['_GETMESSAGESREQUEST']._serialized_end=144
  _globals['_GETMESSAGESRESPONSE']._serialized_start=146
  _globals['_GETMESSAGESRESPONSE']._serialized_end=207
  _globals['_MESSAGE']._serialized_start=209
  _globals['_MESSAGE']._serialized_end=254
  _globals['_MINITWITTER']._serialized_start=257
  _globals['_MINITWITTER']._serialized_end=434
# @@protoc_insertion_point(module_scope)
